    - name: Copying mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Installing mongodb 
      ansible.builtin.package:
        name: mongodb-org 
        state: present

    - name: Update mongodb visability
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: starting mongodb
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Download and Extract mongodb
      ansible.builtin.unarchive:
        src: "https://github.com/stans-robot-project/mongodb/archive/main.zip"
        dest: /tmp
        remote_src: yes        