- name: Demo on package installation 
  hosts: all                               # Privilege Escalation
  tasks: 
    - name: Installing nginx 
      ansible.builtin.package:
        name: nginx 
        state: present
